name: Commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: fetch all issues then rebuild and commit/push
      env:
        ACCESS_TOKEN:  ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY:  ${{ secrets.PUBLISH_REPOSITORY }}
      run: npm run prepare && npm run build && npm run publish