name: Issue

on:
  issues:
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: fetch all issues then rebuild and commit/push
      run: npm run fetch && npm run build && npm run commit