name: Commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: workflow
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn install
      run: yarn --frozen-lockfile
    - name: githublog:prepare
      env:
        ACCESS_TOKEN:  ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY:  ${{ secrets.PUBLISH_REPOSITORY }}
      run: yarn githublog:prepare